// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI work (migrate, db pull, studio) goes over Neon's *direct* endpoint:
    // the pooled one is PgBouncer in transaction mode, which cannot hold the
    // session-level advisory lock Prisma Migrate takes. The running app is the
    // opposite case — it uses the pooled URL via the driver adapter in
    // lib/prisma.ts. `neon link` writes both into .env.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
